### ISSUE TITLE
Implement discovery of feed information

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/XRay#1]
So far I have not found a reliable pattern to determine the author of an h-feed. I think there needs to be an alternate version of the authorship discovery written for feeds.

**Comment by aaronpk** [comment]
Examples:

* http://www.rmendes.net/tag/indieweb
* http://aaronparecki.com/tag/indieweb
* http://aaronparecki.com/
* http://tantek.com/

**Comment by aaronpk** [comment]
https://chat.indieweb.org/2016-07-14#t1468527705078000

I may not need to know the author of the feed.

* tantek: a feed is nothing more than a collection of posts
* tantek: posts have actual authorship, not feeds
* aarnonpk: maybe the thing i'm thinking of is determining whether the URL i'm looking at is a profile URL
* aaronpk: http://twitter.com/t is a profile and a list of posts
* aaronpk: if I want to make a page that looks like that, but is generated by parsing the data on tantek.com, how do I find what profile info to include for the page?
* tantek: in that case, they question is (should be) one of - does this page have a representative h-card

**Comment by sebsel** [comment]
I really like XRays way of storing things (flat, knowing which properties will be string or array, and the `rels` list), and I wanted to use it with my reader. Having it as a library with #17 would be nice for that, but parsing the whole h-feed at once is also very handy.

So, allow me to brainstorm / share some h-feed stuff I learned with [sebsel/lees](https://github.com/sebsel/lees) :)

* I agree: the feed does not have to have an author. It can be used to define the author of the posts, but the feed itself can be authorless. Example of a mixed h-feed is  Twitter > HTML through [Granary](https://granary-demo.appspot.com/).

* Different ways of presenting:
  1. have a `children` property with an array `[]` of objects `{}` that are just what you get in `data` when you look at a h-entry
  2. have a `children` property with an array `[]` of urls, and put the h-entry objects in `refs`

* Some h-feeds have no `u-url` for each h-entry. This makes it impossible to do 2. in those cases. But it might not be XRays task to fix that.
  (Same for `dt-published`. A lot of WP sites have `hentry` class with sometimes a `article-name` class, but dropped the rest of the Mf1. Again: might not be XRays task to fix that.)

* what to do with `h-event` and `h-review` within the `h-feed`? -> have to detect type for each child. 

* when looking at a home page (i.e. aaronparecki.com), I get a card, which is great because that's the main object on that page. But when using XRay in a [/reader](https://indieweb.org/reader), I want a feed. Would be nice to have a `type=feed` parameter, to point XRay to the type of data you are looking for.

* Once you go h-feed, should you go RSS/Atom?

(Made this my first manual Github POSSE. [Original](https://seblog.nl/2017/01/31/2/reply))

**Comment by aaronpk** [comment]
Done in 05f7d9c86cb663f0d91773d32d4a0bb5565bbfd8
