### ISSUE TITLE
Retweets keep their 'photo' field

### ISSUE THREAD

**Issue by sebsel** [aaronpk/XRay#27]
I noticed retweets 'lose' their `content` field, and only have a `repost-of` field, that you can lookup via the `rels`. But: when the retweeted tweet has a `photo`, the retweet also has a `photo` property. Is that on purpose or a bug?

An example of a repost with photo:
https://twitter.com/aukehulst/status/820039442773798912

**Comment by aaronpk** [comment]
hmm interesting. I don't think that was intentional, and is likely a side effect of the fact that Twitter includes the RT'd photo as part of the RT post, probably for clients to have a good fallback. I think I will remove it from the XRay output, since the photo is already present in the `repost-of` object.
