### ISSUE TITLE
invite/mention showed up as an RSVP to me

### ISSUE THREAD

**Issue by EdwardHinkle** [aaronpk/XRay#74]
Chris Aldrich’s [invite post](https://boffosocko.com/2018/07/20/rsvp-to-virtual-homebrew-website-club-meetup-on-july-25-2018/) also contained an RSVP.

Xray/webmention.io translated that as he was RSVP-ing to me. Looking at the markup it seems clear he is RSVP-ing to an event and either mentioning me (simplest solution) or inviting me (harder solution)

This issue is really just proposing that this type of post is first considered a mention, then once there are some more invites in the Wild the work can be done to parse for actual invites.

(Originally published at: https://eddiehinkle.com/2018/07/21/3/reply/)

**Comment by aaronpk** [comment]
Turns out XRay does handle the invitee property already: https://xray.p3k.io/parse?pretty=1&url=https%3A%2F%2Fboffosocko.com%2F2018%2F07%2F20%2Frsvp-to-virtual-homebrew-website-club-meetup-on-july-25-2018%2F

There's a different problem with XRay tho which is that it's using the lastest microformats parser which somehow doesn't see the "rsvp" or "in-reply-to" properties on this post.

Where do you see that this was interpreted as an rsvp to you? There could be something wrong with how webmention.io is interpreting this XRay object.

**Comment by EdwardHinkle** [comment]
Oops something went wrong with my Bridgy syndication so there’s some missing bits to this convo. This issue is being closed because the issue is actually with webmention.io

See &lt;https://aaronparecki.com/2018/07/21/5/&gt; for more info

(Originally published at: https://eddiehinkle.com/2018/07/21/6/reply/)
